export const ROLES = {
  GUEST: 'guest',
  TOURIST: 'tourist',
  TRAVELLER: 'traveller',
  COMPANY: 'company',
  ADMIN: 'admin',
};

export const ENV = {
  JWT_SECRET_KEY: 'JWT_SECRET_KEY',
  JWT_ACCESS_EXPIRATION_TIME: 'JWT_ACCESS_EXPIRATION_TIME',
  JWT_REFRESH_EXPIRATION_TIME: 'JWT_REFRESH_EXPIRATION_TIME',

  MONGODB_URI: 'MONGODB_URI',

  CLIENT_URL: 'CLIENT_URL',
  SERVER_URL: 'SERVER_URL',

  SERVER_PORT: 'SERVER_PORT',

  EMAIL_HOST: 'EMAIL_HOST',
  EMAIL_PORT: 'EMAIL_PORT',
  EMAIL_USER: 'EMAIL_USER',
  EMAIL_PASSWORD: 'EMAIL_PASSWORD',
};

export const COOKIE = {
  REFRESH_TOKEN: 'refreshToken',
};

export const LS = {
  ACCESS_TOKEN: 'ACCESS_TOKEN',
};
